#!/bin/sh

#--------------------------------------------------------------------
# Homebrew Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Update Homebrew and installed packages
    "brew:update")
        echo "Updating Homebrew and its installed packages..."
        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}brew update; brew upgrade; brew upgrade --cask; brew cleanup;\n${NC}"
        fi
        if ! brew update; then
            echo "${RED}Homebrew update failed${NC}"
            exit 1
        fi
        if ! brew upgrade; then
            echo "${RED}Homebrew upgrade failed${NC}"
            exit 1
        fi
        if ! brew upgrade --cask; then
            echo "${RED}Homebrew cask upgrade failed${NC}"
            exit 1
        fi
        if ! brew cleanup; then
            echo "${RED}Homebrew cleanup failed${NC}"
            exit 1
        fi
    ;;

esac
